### ISSUE TITLE
a2civictech meetup for Monday 27 April 2015, 7pm at Pizza Pino's

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#103]
Agenda

Introductions

Possible agenda

- [ ] City of Ann Arbor fiber network buildout ( #99 )
- [ ] Parking ticket data ( #104 )
- [ ] Automated license plate reader data
- [ ] Fire hydrant data FOIA deposit letter ( #101  )
- [ ] Audio output from City Hall for a2 council meetings
- [ ] Gelman plume (Roger Rayle) ( #105 )
- [ ] Stoplight timing ( Robert Klingler )

New

- [ ] eWashtenaw improvements
- [ ] western Washtenaw township fiber / wireless buildout

Announcements

- [ ] Jobs/contracts offered/wanted
- [ ] Events

**Comment by vielmetti** [comment]
Good meeting, attendees include Andy Brush, Roger Rayle, Robert Klingler, Gary (U Toledo), Larry Works, Ed Vielmetti.

**Comment by vielmetti** [comment]
Scheduling the next one.
