### ISSUE TITLE
Pipeline, Rover Pipeline tracking

### ISSUE THREAD

**Issue by vielmetti** [a2civictech/a2civictech#160]
Noted at http://arborwiki.org/Rover_Pipeline and needing more information. 

- [ ] Identify proposed route
- [ ] Which townships does it go through
- [ ] Ask each township for records

**Comment by vielmetti** [comment]
Federal source of this information is PHMSA https://www.phmsa.dot.gov

County source of this information would be deeds, easements, aerial photos. Start with MapWashtenaw https://www.washtenaw.org/1197/MapWashtenaw

At the township level, look for meeting records, agendas and minutes and supporting documents.
